### ISSUE TITLE
第7回の発表内容について

### ISSUE THREAD

**Issue by hururtoriya** [prml-seminar/prml-seminar#11]
こんにちは、 次回は9月の最終金曜日に第7会を開催予定です。
二ヶ月間が開くのでガシッとした発表を期待しています。

**Comment by hururtoriya** [comment]
今まで2章を飛ばして他の章を学んだりしてたんですが、今回2章に取り組んで自分の確率関係の自力の無さをひしひしと感じてしまったので、次回は良い機会なので2章を網羅的に解説した発表をします。
:fire:  :fire:  :fire: 
この夏 :sunny:  統計学びます :rocket: 
- [統計学入門](http://www.amazon.co.jp/exec/obidos/ASIN/4130420658)
- [自然科学の統計学](http://www.amazon.co.jp/%E8%87%AA%E7%84%B6%E7%A7%91%E5%AD%A6%E3%81%AE%E7%B5%B1%E8%A8%88%E5%AD%A6-%E5%9F%BA%E7%A4%8E%E7%B5%B1%E8%A8%88%E5%AD%A6-%E6%9D%B1%E4%BA%AC%E5%A4%A7%E5%AD%A6%E6%95%99%E9%A4%8A%E5%AD%A6%E9%83%A8%E7%B5%B1%E8%A8%88%E5%AD%A6%E6%95%99%E5%AE%A4/dp/4130420674/)

**Comment by junpeitsuji** [comment]
今のところの予定ですが，下巻の「カーネル法（タイトルこれだったっけ？）」のあたりを勉強して発表したいと思っています。
なんとなくこれまで，苦手意識があって触らずにいた部分なので，夏休みに解決したいです。

**Comment by hururtoriya** [comment]
@junpeitsuji  :+1:  ありがとうございます!

**Comment by hururtoriya** [comment]
MLSSの前半が終わったのですが、MLSSの内容が予想以上に濃いのでそちらに専念したいと思います。
