### ISSUE TITLE
#8 の発表内容

### ISSUE THREAD

**Issue by hururtoriya** [prml-seminar/prml-seminar#12]
紹介論文や発表内容について語りましょう :tada: 
http://cs-cafe.connpass.com/event/20649/

**Comment by hururtoriya** [comment]
https://www.hal.t.u-tokyo.ac.jp/~matsui/multimedia/index.html
ACMMM2015のまとめか、ICCV2015で面白そうな論文見つけて発表します。
もしくはECCV2014の論文で良さそうなのあったので、2015で見つからなかったらそっちにします
:+1:

**Comment by hururtoriya** [comment]
@HiroyoshiIto 論文紹介するぞ!!

**Comment by hururtoriya** [comment]
今回から着実にパターン認識と機械学習の本を読み進めていきます。

## 第2章 確率分布    
- 担当 @hurutoriya
- 2.1 2値変数 ~ 2.2 多値変数
- p65-76
***
- 担当 @HiroyoshiIto
- 2.3 ガウス分布 ~ 2.3 周辺ガウス分布
- p65-76

**Comment by hururtoriya** [comment]
## 論文紹介
- @HiroyoshiIto
- WWW2014
-[ A Time-based Collective Factorization for Topic Discovery and Monitoring in News](http://homepages.ulb.ac.be/~amantrac/WebPage/papers/www2014-timebasedfactorization.pdf)

**Comment by hururtoriya** [comment]
参加者各位 :mega:
@Hiroyoshiito
@himkt
ドワンゴが先週公開したプレゼン共有サイトが面白そうなので試用してみても良いですか?
http://niconare.nicovideo.jp/
> プレゼンスライドではなく、プレゼンを共有するサービス

**Comment by hururtoriya** [comment]
@himkt さん
読む論文 :page_facing_up:  のタイトルが決定したら、
- カンファレンス名
- タイトル、URL
を書き込んでくれると助かります!!  :bow:

**Comment by himkt** [comment]
大変申し訳ないのですが今回何も読んだものを持って行けなそうですどうか許してください

**Comment by hururtoriya** [comment]
@himkt :sob: 了解です :+1:

**Comment by hururtoriya** [comment]
### 論文紹介
- @hurutoriya
- ICML2003
- [Semi-Supervised Learning Using Gaussian Fields and Harmonic Functions](http://mlg.eng.cam.ac.uk/zoubin/papers/zgl.pdf)
