### ISSUE TITLE
第9回の発表内容について話し合いましょう

### ISSUE THREAD

**Issue by hururtoriya** [prml-seminar/prml-seminar#13]
- http://cs-cafe.connpass.com/event/22701/

:thought_balloon:対象論文とPRML本の割当について話しましょう:thought_balloon:

次回は僕がIBIS2015の日程とかぶっているため、日取りを後ろにずらしました。
2015年最後の開催になると思います。

**Comment by kento-tajiri** [comment]
"Vanishing Component Analysis",Roi Livni, et al.ICML'15の論文紹介やります！

**Comment by hururtoriya** [comment]
論文紹介してくれてありがとうございます🤗
:+1: 質疑含めて20分ぐらいでよろしくお願いします！！！

**Comment by hururtoriya** [comment]
@HiroyoshiIto  読む論文きめよう !!
