### ISSUE TITLE
#10 論文読み会

### ISSUE THREAD

**Issue by hururtoriya** [prml-seminar/prml-seminar#14]
http://cs-cafe.connpass.com/event/26261/

PRML勉強会第10回の開催です :smile: 

2015/02/05 18:30~ で論文読み会をメインに勉強会開催します。
ご興味のある方、ご参加下さい

cc @HiroyoshiIto 論文読むぞ!!!!

**Comment by hururtoriya** [comment]
もしお時間あればよろしくおねがいします!! 
@cocuh @getumen junpeitsuji

**Comment by hururtoriya** [comment]
読みます。
## Spectral Clustering and Ranking
- KDD2015 Best student paper award
- http://www.cs.cornell.edu/~bindel//blurbs/graphspec.html
- Author : Xie, Bindel, Demers, and Gehrke
- @huturoriya

**Comment by HiroyoshiIto** [comment]
これに決めた！
#TM-LDA: Efficient Online Modeling of the Latent Topic Transitions in Social Media
-KDD2012
-http://www.mathcs.emory.edu/~benzi/Web_papers/TM-LDA.pdf
-Author: Yu Wang, Eugene Agichtein, Michele Benzi
-@HiroyoshiIto

**Comment by hururtoriya** [comment]
@HiroyoshiIto :+1:
