### ISSUE TITLE
talk about #11 

### ISSUE THREAD

**Issue by hurutoriya** [prml-seminar/prml-seminar#15]
## 勉強会 Check List
- [x] 日程調整(基本的に金曜日 18:30~)
- [x] 会場の準備(部屋予約申請・変換ケーブル)
- [x] 発表の打ち合わせ(紹介論文、担当章、発表者の設定)
- [x] SNS告知・ログ作成(Show Notes, Togetter)

**Comment by hurutoriya** [comment]
@HiroyoshiIto 
明日の金曜日、参加できなくなったので日程調整してもらっても良いですか?
:sob: 
https://chouseisan.com/s?h=e2577b40bd6148d49f14eb6c473d9ffb

**Comment by hurutoriya** [comment]
@HiroyoshiIto 調整さんの結果見た感じ、04/18日はどうですか? :smile:

**Comment by HiroyoshiIto** [comment]
@hurutoriya 大丈夫ですよ〜

**Comment by hurutoriya** [comment]
@HiroyoshiIto :+1: 
http://cs-cafe.connpass.com/event/28502/ ページ公開しました。参加登録お願いします :smile: 
紹介論文決まったらまた教えて下さい。

**Comment by hurutoriya** [comment]
Dhillon, Inderjit S., Yuqiang Guan, and Brian Kulis. "Kernel k-means: spectral clustering and normalized cuts." Proceedings of the tenth ACM SIGKDD international conference on Knowledge discovery and data mining. ACM, 2004. を読みます

**Comment by hurutoriya** [comment]
@HiroyoshiIto  読む論文決まった?

**Comment by HiroyoshiIto** [comment]
Simultaneous Discovery of
Common and Discriminative Topics
via Joint Nonnegative Matrix Factorization

http://delivery.acm.org/10.1145/2790000/2783338/p567-kim.pdf?ip=133.51.122.221&id=2783338&acc=ACTIVE%20SERVICE&key=D2341B890AD12BFE%2E5A1FE8BDE322CB75%2EF320D63CBDBFFB04%2E4D4702B0C3E38B35&CFID=742923465&CFTOKEN=51923465&__acm__=1458298313_cf26c436407bfdfc4d77e13bb063fb39
