### ISSUE TITLE
#6 の発表内容について語り合いましょう

### ISSUE THREAD

**Issue by hururtoriya** [prml-seminar/prml-seminar#6]
![](https://lh3.googleusercontent.com/T4EwPzUsZSJ3E0Ox00Gv7Zo7rzd4FCSUqgklSxXbp0hb=w775-h311-no)
http://cs-cafe.connpass.com/event/17162/
ざっくり話しあいましょう :+1:

**Comment by rilmayer** [comment]
こんにちは～。発表予定です～。

**Comment by hururtoriya** [comment]
@rilmayer :+1:  アイコンがTwitterに比べると爽やかすぎて驚きましたw
現状なんですが、PRML本の進捗はPRML本の2章まで進んでいる感じです。
そこから確率や細かい話に広がっていっています。

## 発表形式

当初はPRML本の輪講形式だったんですが教科書の焼き直しにならないようにするために、
今の勉強会の進行スタイルは、PRML本(上)~2章までが皆読んでる前提で
1. PRML本で学ぶ中で詰まった点(確率論や実装など,etc)について発表する
2. 機械学習を勉強する上で気になるポイント(学んでいて面白かった論文や知識)やなんか作ったやったよ!

の２つのパターンになってます。

**Comment by rilmayer** [comment]
では、機械学習的な知識織り込んで、なんか作りました的な発表しようかと思います～。

**Comment by hururtoriya** [comment]
@rilmayer  分かりました~ :smile:  
タイトルと発表の目安時間決まったら教えて下さい。
発表時間は最大20分まで大丈夫です。

**Comment by hururtoriya** [comment]
PRML本の進行状況としては2章の途中から発散してるので、今回の勉強会で2章を終わらせたいなとおもいます。　
2章をまとめて、自分が気になったところについて突っ込んだ発表にしようかなと思います。

**Comment by rilmayer** [comment]
タイトルは「文書群のクラスタリング＋ラベル付けを自動で行う（K-meansと主成分分析の応用）」でお願いします。
時間は10分くらいかなと思います。
細かく話そうと思えば2倍くらい長くできると思うので、その辺は全体に合わせます～。

内容的に完全に下巻ですが、大丈夫でしょうか。汗

**Comment by hururtoriya** [comment]
@rilmayer 
基本的に1章から順序立ててやっているわけではないので、大丈夫です~

- ＊発表の空気感は分からない所や質問があればその時にガンガン質問していくスタイルなので、参加者が`ガンガンいこうぜ`状態になると自然と詳しく話す事になると思います :smile: 
- 発表中は集中したい!  → 後からまとめて質問してほしい でもOKです :+1: 

対応する章・節の明記よろしくおねがいします。
発表者として参加してくれて、本当にありがたいございます。

**Comment by rilmayer** [comment]
お返事遅くなっちゃってすみません～。
対応する章・節はここに書けばいいのかな？

今回の発表に対応するところは
9章　9.1 K-meansクラスタリング
12章　12.1 主成分分析
です～。（下巻でスミマセン・・・

いやいや、むしろこういう会に誘ってくれてありがたいです！
今後もどうぞヨロシク！

**Comment by hururtoriya** [comment]
@rilmayer :+1:
